- hosts: nodes
  become: yes
  tasks:
  - name: ensure docker is installed
    apt: 
      name: docker.io
      state: latest

  - name: ensure docker is installed
    apt: 
      name: docker-compose
      state: latest
  
  - name: Added users to docker group
    user:
      name: vagrant
      group: docker





